1

diff --git a/runsqlbackup b/runsqlbackup
--- a/runsqlbackup
+++ b/runsqlbackup
@@ -1,14 +1,7 @@
 #!/bin/bash
 
-# Đọc cấu hình từ file my-config.cnf trước
-MY_CONFIG="/etc/automysqlbackup/my-config.cnf"
-if [ -f "$MY_CONFIG" ]; then
-    source "$MY_CONFIG"
-fi
-
-# Sau đó đọc cấu hình chính từ main.cnf
-CONFIG_FILE="/etc/automysqlbackup/conf.d/main.cnf"
-source "$CONFIG_FILE"
+# Đọc cấu hình chính từ main.cnf
+CONFIG_FILE="/etc/automysqlbackup/mysqlbackup.cnf"
 
 if [ ! -f "$CONFIG_FILE" ]; then
   echo "Configuration file not found: $CONFIG_FILE"
@@ -22,7 +15,26 @@ DATE=$(date +%F)
 DAY_OF_WEEK=$(date +%u)  # Ngày trong tuần (1 = Thứ 2, 7 = Chủ nhật)
 LOG_FILE="$BACKUP_DIR/backup_log_$DATE.log"
 
+# Lấy sử dụng mật khẩu SQL
 export MYSQL_PWD=$MYSQL_PASSWORD
+
+TEST=$(sudo mysql -u $MYSQL_USER)
+
+STATUS=$?
+echo $STATUS
+exit 1;
+if [ $STATUS -ne 0 ]; then
+    echo "MySQL command failed with exit code $STATUS"
+    echo "Error message: $TEST"
+    exit 1
+else
+    echo "MySQL command succeeded"
+    echo "Output: $TEST"
+fi
+
+exit 1
+
+
 
 # Lấy danh sách database cần sao lưu
 DATABASES=$(mysql -u$MYSQL_USER -e "SHOW DATABASES;" | grep -Ev "(Database|$CONFIG_DB_EXCLUDE)")
@@ -40,9 +52,13 @@ for dir in daily weekly monthly; do
   }
 done
 
-sudo chown -R root:root $BACKUP_DIR*
-sudo find $BACKUP_DIR* -type f -exec chmod 644 {} \;
-sudo find $BACKUP_DIR* -type d -exec chmod 755 {} \;
+#sudo chown -R root:root $BACKUP_DIR*
+#sudo find $BACKUP_DIR* -type f -exec chmod 644 {} \;
+#sudo find $BACKUP_DIR* -type d -exec chmod 755 {} \;
+
+echo $MYSQL_PASSWORD
+echo $MYSQL_USER
+
 
 SUCCESSFUL_BACKUPS=""
 FAILED_BACKUPS=""
